spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: 1323!Q@#EMSD%$^
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 指定namespace
        namespace: 68dc03c0-048d-48c4-81e3-b7d1b34556e5
        # 指定集群名称
        cluster-name: BJ
        # 元数据
        metadata:
          version: v1
          target-version: v1

    sentinel:
      transport:
        # 指定sentinel控制台
        dashboard: http://localhost:8888
      filter:
        # 关闭对springmvc端点的保护
#        enabled: false
        enabled: true

  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true

server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.tzword.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      default: #default为全局配置，如果写服务名为单个服务名的配置
        loggerLevel: full

  # 使feign使用httpclient，可以配置连接池提高性能，替换默认的URLConnetion的客户端，当然这里也可以使用okhttp
  httpclient:
    enabled: true
    #最大连接数的大小
    max-connections: 200
    #单个路由的最大连接数
    max-connections-per-route: 20
  sentinel:
    enabled: true

#添加sentinel依赖后 暴露/actuator/sentinel端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

resttemplate:
  # SentinelRestTemplate开关
  sentinel:
    enabled: false